[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "composer", "nodejs_20"]

[phases.install]
cmds = ["composer install --ignore-platform-reqs --no-interaction --no-dev", "npm install --ignore-scripts"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"